
version: 2.1
jobs:
  build:
    docker:
      - image: l.gcr.io/google/bazel:3.4.1
    steps:
      - checkout
      - run:
          name: Execute bazel
          command: |-
               gradlew bootBuildImage --imageName=wixpress/greyhound-app
               
              # Set environment variables
              # Install Bazelisk
              rm /usr/local/bin/bazel
              curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64"
              mv bazelisk-linux-amd64 /usr/bin/bazel
              chmod +x /usr/bin/bazel
              which bazel

              # Execute bazel
              bazel --bazelrc=.cirrus.bazelrc test -k //...
